import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body
        className={` antialiased bg-background text-foreground flex justify-center min-h-screen`}
      >
        <div className="w-full bg-foreground max-w-[402px]">
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
